import { ratio } from "fuzzball"

// > document.querySelectorAll('div.license-info > strong').forEach(e => console.log(e.innerText))
const pluginsIhave = [
  "ACME Audio Opticom XLA-3",
  "ADPTR AUDIO HYPE",
  "ADPTR AUDIO Metric AB",
  "ADPTR AUDIO SCULPT",
  "ADPTR AUDIO Streamliner",
  "AMEK EQ 200",
  "AMEK EQ 250",
  "AMEK Mastering Compressor",
  "Ampeg SVT-VR Classic",
  "Bettermaker EQ232D",
  "Bettermaker Passive Equalizer",
  "Black Box Analog Design HG-2",
  "Black Box Analog Design HG-2MS",
  "Brainworx bx_2098 EQ",
  "Brainworx bx_aura",
  "Brainworx bx_bassdude",
  "Brainworx bx_boom V3",
  "Brainworx bx_cleansweep Pro",
  "Brainworx bx_clipper",
  "Brainworx bx_console AMEK 200",
  "Brainworx bx_console AMEK 9099",
  "Brainworx bx_console Focusrite SC",
  "Brainworx bx_console N",
  "Brainworx bx_console SSL 4000 G",
  "Brainworx bx_console SSL 9000 J",
  "Brainworx bx_control V2",
  "Brainworx bx_delay 2500",
  "Brainworx bx_digital V2",
  "Brainworx bx_digital V3",
  "Brainworx bx_glue",
  "Brainworx bx_limiter",
  "Brainworx bx_masterdesk",
  "Brainworx bx_masterdesk PRO",
  "Brainworx bx_masterdesk True Peak",
  "Brainworx bx_oberhausen",
  "Brainworx bx_opto",
  "Brainworx bx_refinement",
  "Brainworx bx_refinement V3",
  "Brainworx bx_rockergain100",
  "Brainworx bx_rockrack V3",
  "Brainworx bx_rooMS",
  "Brainworx bx_saturator V2",
  "Brainworx bx_stereomaker",
  "Brainworx bx_subsynth",
  "Brainworx bx_townhouse Buss Compressor",
  "Chandler Limited GAV19T",
  "Cherry Audio Voltage Modular Ignite",
  "Dangerous Music BAX EQ",
  "DS Audio TANTRA 2",
  "DS Audio Thorn",
  "elysia alpha compressor",
  "elysia karacter",
  "elysia mpressor",
  "elysia museq",
  "elysia nvelope",
  "elysia Phil's Cascade",
  "fiedler audio stage",
  "Kiive Audio Tape Face",
  "Kiive Audio XTComp",
  "Kiive Audio Xtressor",
  "Knif Audio Knifonium",
  "Knif Audio Soma",
  "Lindell Audio 354E",
  "Lindell Audio 50 Series",
  "Lindell Audio 69 Series",
  "Lindell Audio 6X-500",
  "Lindell Audio 7X-500",
  "Lindell Audio 80 Series",
  "Lindell Audio 902 De-Esser",
  "Lindell Audio ChannelX",
  "Lindell Audio MBC",
  "Lindell Audio MU-66",
  "Lindell Audio PEX-500",
  "Lindell Audio SBC",
  "Lindell Audio TE-100",
  "Looptrotter SA2RATE 2",
  "Louder Than Liftoff SILVER BULLET mk2",
  "Mäag Audio EQ2",
  "Mäag Audio EQ4",
  "Maor Appelbaum Mastering & Hendyamps THE OVEN",
  "Millennia NSEQ-2",
  "Mixland Vac Attack",
  "NEOLD BIG AL",
  "NEOLD OLDTIMER",
  "NEOLD U17",
  "NEOLD U2A",
  "NEOLD V76U73",
  "NEOLD WARBLE",
  "NEOLD WUNDERLICH",
  "PA FREE bx_boom!",
  "PA FREE bx_cleansweep V2",
  "PA FREE bx_distorange",
  "PA FREE bx_greenscreamer",
  "PA FREE bx_masterdesk Classic",
  "PA FREE bx_megasingle",
  "PA FREE bx_metal2",
  "PA FREE bx_meter",
  "PA FREE bx_opto Pedal",
  "PA FREE bx_rockrack V3 Player",
  "PA FREE bx_solo",
  "PA FREE bx_subfilter",
  "PA FREE bx_tuner",
  "PA FREE bx_yellowdrive",
  "PA FREE Double MS",
  "PA FREE Free Ranger",
  "PA FREE niveau filter",
  "ProAudioDSP DSM V3",
  "Purple Audio MC77",
  "Shadow Hills Mastering Compressor",
  "Shadow Hills Mastering Compressor Class A",
  "SPL De-Verb Plus",
  "SPL EQ Ranger Plus",
  "SPL HawkEye",
  "SPL IRON",
  "SPL Mo-Verb Plus",
  "SPL Passeq",
  "SPL PQ",
  "SPL Transient Designer",
  "SPL Transient Designer Plus",
  "SPL TwinTube",
  "SPL Vitalizer MK2-T",
  "Three-Body Technology Cenozoix Compressor",
  "Three-Body Technology Kirchhoff-EQ",
  "Three-Body Technology Trinity Shaper",
  "TOMO Audiolabs LISA",
  "Unfiltered Audio Bass-Mint",
  "Unfiltered Audio Battalion",
  "Unfiltered Audio BYOME",
  "Unfiltered Audio Dent",
  "Unfiltered Audio Dent 2",
  "Unfiltered Audio Fault",
  "Unfiltered Audio G8",
  "Unfiltered Audio Indent 2",
  "Unfiltered Audio LO-FI-AF",
  "Unfiltered Audio Needlepoint",
  "Unfiltered Audio SILO",
  "Unfiltered Audio SpecOps",
  "Unfiltered Audio TRIAD",
  "Unfiltered Audio Zip",
  "Vertigo VSC-2",
  "Vertigo VSM-3",
  "WEDGE FORCE Matcha",
]

//  > document.querySelectorAll('ul > li.product-title > a').forEach(e => console.log(e.innerText))
const allPlugins = [
  "254E",
  "354E",
  "50 Series",
  "69 Series",
  "6X-500",
  "7X-500",
  "80 Series",
  "800RB",
  "902 De-Esser",
  "alpha compressor",
  "Attacker Plus",
  "B-15N",
  "Bass-Mint",
  "Battalion",
  "BAX EQ",
  "BE-100",
  "BiG",
  "BIG AL",
  "Blocks Primes",
  "BM60",
  "Bus Compressor",
  "Buxom Betty",
  "bx_2098 EQ",
  "bx_aura",
  "bx_bassdude",
  "bx_blackdist2",
  "bx_bluechorus2",
  "bx_boom V3",
  "bx_boom!",
  "bx_cleansweep Pro",
  "bx_cleansweep V2",
  "bx_clipper",
  "bx_console AMEK 200",
  "bx_console AMEK 9099",
  "bx_console Focusrite SC",
  "bx_console N",
  "bx_console SSL 4000 E",
  "bx_console SSL 4000 G",
  "bx_console SSL 9000 J",
  "bx_control V2",
  "bx_crispytuner",
  "bx_delay 2500",
  "bx_digital V3",
  "bx_distorange",
  "bx_dynEQ V2",
  "bx_enhancer",
  "bx_glue",
  "bx_greenscreamer",
  "bx_hybrid V2",
  "bx_limiter",
  "bx_limiter True Peak",
  "bx_masterdesk",
  "bx_masterdesk Classic",
  "bx_masterdesk PRO",
  "bx_masterdesk True Peak",
  "bx_megadual",
  "bx_megasingle",
  "bx_metal2",
  "bx_meter",
  "bx_oberhausen",
  "bx_opto",
  "bx_opto Pedal",
  "bx_panEQ",
  "bx_refinement",
  "bx_refinement V3",
  "bx_rockergain100",
  "bx_rockrack V3",
  "bx_rockrack V3 Player",
  "bx_rooMS",
  "bx_saturator V2",
  "bx_shredspread",
  "bx_solo",
  "bx_stereomaker",
  "bx_subfilter",
  "bx_subsynth",
  "bx_townhouse Buss Compressor",
  "bx_tuner",
  "bx_XL V2",
  "bx_XL V3",
  "bx_yellowdrive",
  "BYOME",
  "C502V",
  "Cenozoix Compressor",
  "ChannelX",
  "Character",
  "Chop Shop",
  "De-Esser Collection",
  "De-Verb Plus",
  "dearVR MUSIC",
  "Dent 2",
  "Double MS",
  "DrumXchanger",
  "DS-40",
  "DSM V3",
  "E646 VS",
  "E765 RT",
  "EQ 200",
  "EQ 250",
  "EQ Ranger Plus",
  "EQ2",
  "EQ232D",
  "EQ4",
  "EQ4 MS",
  "Fault",
  "Flanger",
  "Flesh",
  "FM8",
  "Form",
  "Free Ranger",
  "G8",
  "GAV19T",
  "Guitar Rig 7 Pro",
  "HawkEye",
  "Herbert",
  "HG-2",
  "HG-2MS",
  "HG-Q",
  "Hydro",
  "HYPE",
  "Indent 2",
  "Instant Delay",
  "IRON",
  "karacter",
  "Keemun",
  "Kick Ninja",
  "Kirchhoff-EQ",
  "Knifonium",
  "Kolor",
  "Kontour",
  "LION",
  "LISA",
  "LO-FI-AF",
  "Machine Head",
  "Magnum-K",
  "MASSIVE",
  "Mastering Compressor",
  "Mastering Compressor Class A",
  "Matcha",
  "MBC",
  "MC77",
  "MEGA Monthly",
  "MEGA Sampler",
  "MEGA Yearly",
  "Metric AB",
  "Mo-Verb Plus",
  "Molekular",
  "Monark",
  "Mono Upmix",
  "mpressor",
  "MU-66",
  "museq",
  "Natalus DSCEQ",
  "Nectar 4 Advanced",
  "Nectar 4 Elements",
  "Nectar 4 Standard",
  "Needlepoint",
  "niveau filter",
  "NSEQ-2",
  "nvelope",
  "OLDTIMER",
  "Oolong",
  "Opticom XLA-3",
  "Overdrive Supreme 50",
  "Ozone 11 Advanced",
  "Ozone 11 Elements",
  "Ozone 11 Standard",
  "Passeq",
  "Passive Equalizer",
  "PEX-500",
  "Phil's Cascade",
  "PQ",
  "Prism",
  "Psyche Delay",
  "PT100",
  "Razor",
  "Reaktor Spark R2",
  "Rounds",
  "SA2RATE 2",
  "Sandman",
  "Sandman Pro",
  "Savage 120",
  "SBC",
  "SCULPT",
  "SE100",
  "SILO",
  "SILVER BULLET mk2",
  "Soma",
  "Spatial Creator",
  "SpecOps",
  "splat",
  "stage",
  "STD-1 Stereo Tapped Delay",
  "Streamliner",
  "Sub Ninja",
  "Super 8",
  "SVT-3PRO",
  "SVT-VR",
  "SVT-VR Classic",
  "TAILS",
  "TANTRA 2",
  "Tape Face",
  "Tape Wobble",
  "TCL-2",
  "TE-100",
  "THE OVEN",
  "Thorn",
  "Train II",
  "Transient Designer Plus",
  "Trash",
  "TRIAD",
  "Trinity Shaper",
  "TRK-01",
  "TwinTube",
  "U17",
  "U2A",
  "V-4B",
  "V76U73",
  "Vac Attack",
  "VH4",
  "Vitalizer MK2-T",
  "Vocal Enhancer",
  "VSC-2",
  "VSM-3",
  "VSS-2",
  "WARBLE",
  "Wavesurfer",
  "WUNDERLICH",
  "XTComp",
  "Zip",
]

const pluginsIDontHave = new Set(allPlugins)

allPlugins.forEach((plugin) => {
  let found = false
  pluginsIhave.forEach((pluginIHave) => {
    if (pluginIHave.includes(plugin)) {
      found = true
      pluginsIDontHave.delete(plugin)
    }
  })
})

console.log("Plugins I don't have: ", pluginsIDontHave)